class Enchantment {
    constructor(name, maxLevel, itemMultiplier, bookMultiplier, conflictGroups) {
        this.name = name;
        this.maxLevel = maxLevel;
        this.itemMultiplier = itemMultiplier;
        this.bookMultiplier = bookMultiplier;
        this.conflictGroups = conflictGroups;
    }
}

class Tool {
    constructor(name, applicableEnchantmentNames) {
        this.name = name;
        this.applicableEnchantmentNames = applicableEnchantmentNames;
    }
}

class DataProvider {
    constructor() {
        this.enchantments = [
            new Enchantment("Protection", 4, 1, 1, [0]),
            new Enchantment("Fire Protection", 4, 2, 1, [0]),
            new Enchantment("Feather Falling", 4, 2, 1, null),
            new Enchantment("Blast Protection", 4, 4, 2, [0]),
            new Enchantment("Projectile Protection", 4, 2, 1, [0]),
            new Enchantment("Thorns", 3, 8, 4, null),
            new Enchantment("Respiration", 3, 4, 2, null),
            new Enchantment("Depth Strider", 3, 4, 2, [3]),
            new Enchantment("Aqua Affinity", 1, 4, 2, null),
            new Enchantment("Sharpness", 5, 1, 1, [1]),
            new Enchantment("Smite", 5, 2, 1, [1]),
            new Enchantment("Bane of Arthropods", 5, 2, 1, [1]),
            new Enchantment("Knockback", 2, 2, 1, null),
            new Enchantment("Fire Aspect", 2, 4, 2, null),
            new Enchantment("Looting", 3, 4, 2, null),
            new Enchantment("Efficiency", 5, 1, 1, null),
            new Enchantment("Silk Touch", 1, 8, 4, [2]),
            new Enchantment("Unbreaking", 3, 2, 1, null),
            new Enchantment("Fortune", 3, 4, 2, 2),
            new Enchantment("Power", 5, 1, 1, null),
            new Enchantment("Punch", 2, 4, 2, null),
            new Enchantment("Flame", 1, 4, 2, null),
            new Enchantment("Infinity", 1, 8, 4, 4),
            new Enchantment("Luck of the Sea", 3, 4, 2, null),
            new Enchantment("Lure", 3, 4, 2, null),
            new Enchantment("Frost Walker", 2, 4, 2, [3]),
            new Enchantment("Mending", 1, 4, 2, [4]),
            new Enchantment("Impaling", 5, 2, 1, null),
            new Enchantment("Riptide", 3, 4, 2, [5, 6]),
            new Enchantment("Loyalty", 3, 1, 1, [5]),
            new Enchantment("Channeling", 1, 8, 4, [6]),
            new Enchantment("Multishot", 1, 4, 2, [7]),
            new Enchantment("Piercing", 4, 1, 1, [7]),
            new Enchantment("Quick Charge", 3, 2, 1, null),
            new Enchantment("Sweeping Edge", 3, 4, 2, null),
            new Enchantment("Soul Speed", 3, 8, 4, null),
            new Enchantment("Curse of Binding", 1, 8, 4, null),
            new Enchantment("Curse of Vanishing", 1, 8, 4, null),
        ];
        this.tools = [
            new Tool("Sword", [
                "Sharpness",
                "Smite",
                "Bane of Arthropods",
                "Knockback",
                "Fire Aspect",
                "Looting",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
                "Sweeping Edge",
            ]),
            new Tool("Pickaxe", [
                "Efficiency",
                "Fortune",
                "Silk Touch",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Axe", [
                "Efficiency",
                "Fortune",
                "Silk Touch",
                "Sharpness",
                "Smite",
                "Bane of Arthropods",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Shovel", [
                "Efficiency",
                "Fortune",
                "Silk Touch",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Helmet", [
                "Protection",
                "Fire Protection",
                "Projectile Protection",
                "Blast Protection",
                "Respiration",
                "Aqua Affinity",
                "Thorns",
                "Unbreaking",
                "Mending",
                "Curse of Binding",
                "Curse of Vanishing",
            ]),
            new Tool("Chestplate", [
                "Protection",
                "Fire Protection",
                "Projectile Protection",
                "Blast Protection",
                "Thorns",
                "Unbreaking",
                "Mending",
                "Curse of Binding",
                "Curse of Vanishing",
            ]),
            new Tool("Leggings", [
                "Protection",
                "Fire Protection",
                "Projectile Protection",
                "Blast Protection",
                "Thorns",
                "Unbreaking",
                "Mending",
                "Curse of Binding",
                "Curse of Vanishing",
            ]),
            new Tool("Boots", [
                "Protection",
                "Fire Protection",
                "Projectile Protection",
                "Blast Protection",
                "Feather Falling",
                "Frost Walker",
                "Depth Strider",
                "Thorns",
                "Unbreaking",
                "Mending",
                "Curse of Binding",
                "Curse of Vanishing",
                "Soul Speed",
            ]),
            new Tool("Bow", [
                "Power",
                "Punch",
                "Flame",
                "Infinity",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Crossbow", [
                "Piercing",
                "Multishot",
                "Quick Charge",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Trident", [
                "Impaling",
                "Loyalty",
                "Riptide",
                "Channeling",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Fishing Rod", [
                "Lure",
                "Luck of the Sea",
                "Unbreaking",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Shield", [
                "Unbreaking",
                "Mending",
                "Curse of Vanishing"
            ]),
            new Tool("Hoe", [
                "Efficiency",
                "Fortune",
                "Unbreaking",
                "Silk Touch",
                "Mending",
                "Curse of Vanishing",
            ]),
            new Tool("Book", [
                "Protection",
                "Fire Protection",
                "Feather Falling",
                "Blast Protection",
                "Projectile Protection",
                "Thorns",
                "Respiration",
                "Depth Strider",
                "Aqua Affinity",
                "Sharpness",
                "Smite",
                "Bane of Arthropods",
                "Knockback",
                "Fire Aspect",
                "Looting",
                "Efficiency",
                "Silk Touch",
                "Unbreaking",
                "Fortune",
                "Power",
                "Punch",
                "Flame",
                "Infinity",
                "Luck of the Sea",
                "Lure",
                "Frost Walker",
                "Mending",
                "Curse of Binding",
                "Curse of Vanishing",
                "Impaling",
                "Riptide",
                "Loyalty",
                "Channeling",
                "Multishot",
                "Piercing",
                "Quick Charge",
                "Sweeping Edge",
                "Soul Speed",
            ])
        ];
                       
    }
}